class DataSchemaRAW:
    ROW_ID = "Row ID"
    ORDER_ID = "Order ID"
    ORDER_DATE = "Order Date"
    SHIP_DATE = "Ship Date"
    SHIP_MODE = "Ship Mode"
    CUSTOMER_ID = "Customer ID"
    CUSTOMER_NAME = "Customer Name"
    SEGMENT = "Segment"
    COUNTRY_REGION = "Country/Region"
    CITY = "City"
    STATE = "State"
    POSTAL_CODE = "Postal Code"
    REGION = "Region"
    PRODUCT_ID = "Product ID"
    CATEGORY = "Category"
    SUB_CATEGORY = "Sub-Category"
    PRODUCT_NAME = "Product Name"
    SALES = "Sales"
    QUANTITY = "Quantity"
    DISCOUNT = "Discount"
    PROFIT = "Profit"


class DataSchema:
    ROW_ID = "row_id"
    ORDER_ID = "order_id"
    ORDER_DATE = "order_date"
    SHIP_DATE = "ship_date"
    SHIP_MODE = "ship_mode"
    CUSTOMER_ID = "customer_id"
    CUSTOMER_NAME = "customer_name"
    SEGMENT = "segment"
    COUNTRY_REGION = "country_region"
    CITY = "city"
    STATE = "state"
    POSTAL_CODE = "postal_code"
    REGION = "region"
    PRODUCT_ID = "product_id"
    CATEGORY = "category"
    SUB_CATEGORY = "sub_category"
    PRODUCT_NAME = "product_name"
    SALES = "sales"
    QUANTITY = "quantity"
    DISCOUNT = "discount"
    PROFIT = "profit"
    MONTH_YEAR = "month_year"
